services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=Asia/Kolkata
      - PASSWORD=${PASS}
      - DEFAULT_WORKSPACE=/home/code-server #optional
    volumes:
      - ./code-server/config:/config
      - ./home/code-server:/home/code-server
    ports:
      - 8443:8443
    restart: unless-stopped
