version: "3"
services:
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8888:8080
    volumes:
      - /path/to/storage:/data
      - ./filebrowser:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
    networks:
      - docker_net
