services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - /opt/karakeep/data:/data
    ports:
      - 3090:3000
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      KARAKEEP_VERSION: ${KARAKEEP_VERSION:-release}
      # random string using `openssl rand -hex 32`
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-masterKey}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-supersecretkey}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3090}
      OAUTH_AUTO_REDIRECT: ${OAUTH_AUTO_REDIRECT:-true}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_PROVIDER_NAME: ${OAUTH_PROVIDER_NAME:-Authentik}
      OAUTH_WELLKNOWN_URL: ${OAUTH_WELLKNOWN_URL}
      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.41.0
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /opt/karakeep/meilisearch:/meili_data