version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - USER=${USER}
      - PASS=${PASSWORD}
    volumes:
      - ./transmission/data:/config
      - /path/to/storage/downloads:/downloads
      - /path/to/storage/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - docker_net
