services:
  unbound:
    container_name: unbound
    image: klutchell/unbound
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.xx  # set static IP to be used in pihole
